const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const PlanetsSchema = new Schema({
  id: Number,
  pl_hostname: String,
  pl_letter: String,
  display_name: String,
  description: String,
  discovery_date: String,
  url: String,
  title: String,
  feature_title: String,
  mass_display: String,
  planet_type: String,
  st_dist: Number,
  st_optmag: Number,
  pl_radj: Number,
  pl_rade: Number,
  pl_massj: Number,
  pl_discmethod: String,
  image: String,
  list_image: String,
  short_description: String,
  ranger_feature_id: String,
  ranger_system_id: String,
  ranger_system: Boolean,
  exo_id: String,
  subtitle: String,
  categories: Array,
  pl_kepflag: Boolean,
  pl_facility: String,
  long_description: { type: String, default: null },
});

module.exports = mongoose.model("Planet", PlanetsSchema);

//  "id": 1332,
//       "pl_hostname": "CoRoT-18",
//       "pl_letter": "b",
//       "display_name": "CoRoT-18 b",
//       "description": "CoRoT-18 b is a gas giant exoplanet that orbits a G-type star. Its mass is 3.47 Jupiters, it takes 1.9 days to complete one orbit of its star, and is 0.0295 AU from its star. Its discovery was announced in 2011.",
//       "discovery_date": "2011",
//       "url": "/exoplanet-catalog/1332/corot-18-b/",
//       "title": "CoRoT-18 b",
//       "feature_title": "CoRoT-18 b",
//       "mass_display": "3.47 Jupiters",
//       "planet_type": "Gas Giant",
//       "st_dist": 2495,
//       "st_optmag": 14.868,
//       "pl_radj": 1.31,
//       "pl_rade": 14.68,
//       "pl_massj": 3.47,
//       "pl_discmethod": "Transit",
//       "image": "/assets/content/planets/gasgiant.jpg",
//       "list_image": "/assets/content/planets/gasgiant_sq.jpg",
//       "short_description": "CoRoT-18 b is a gas giant exoplanet that orbits a G-type star. Its mass is 3.47 Jupiters, it takes 1.9 days to complete one orbit of its star, and is 0.0295 AU from its star. Its discovery was announced in 2011.",
//       "ranger_feature_id": "CoRoT-18_b",
//       "ranger_system_id": "CoRoT-18",
//       "ranger_system": false,
//       "exo_id": "CoRoT-18_b",
//       "subtitle": "A giant planet composed mainly of gas",
//       "categories": [],
//       "pl_kepflag": false,
//       "pl_facility": "CoRoT",
//       "long_description": null
